### PR TITLE
added favicon

### PR DESCRIPTION
**Pull request by BBosgraaf**

### CODE REVIEW

**Review by ThijsRaaijmakers — DISMISSED** [review]
LGTM

**Review by ThijsRaaijmakers — APPROVED** [review]
LGTM

**Review by ThijsRaaijmakers — CHANGES_REQUESTED** [review]
FAVICONNNNNNNNNNNNNN

**Review by ThijsRaaijmakers — APPROVED** [review]
LGTM (eindelijk)

**Review by goldo63 — APPROVED** [review]
LGTM!

**Pull request merged**
